sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements-dev.txt

script:
  - pytest --cov-report= --cov=data_loader --cov-config .coveragerc

after_success:
  - CI=true TRAVIS=true coveralls
