sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - pytest --cov-report= --cov=data_loader

after_success:
  - CI=true TRAVIS=true coveralls --verbose
