sudo: false

language: python

python:
  - '3.6'
  - '3.5'
  - '3.4'

install:
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - pytest --cov=data_loader tests

after_success:
  - CI=true TRAVIS=true coveralls
